$axure.loadCurrentPage({
  "url":"page_2.html",
  "generationDate":new Date(1442161483564.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f0e4a82e6090433aa0bcd4283e67c369",
    "type":"Axure:Page",
    "name":"Page 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3870d1b2b41847d697a7e792fe91c96a",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":240},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on (Shape) equal to &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bd70f4f719524170be977338a50e1960"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":100,
              "height":30,
              "loadLocalDefault":true,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":0,
                "b":0,
                "a":1},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"88fd5f2766a2414ea0d27039a9ccb4b3",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd70f4f719524170be977338a50e1960",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CC00},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/page_2/u1.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"1915-1925"}},
{
              "column0":{
                "type":"text",
                "text":"1794-1811"}}],
          "dataProps":["column0"]},
{
          "id":"b986408168f54c759e7a876778397088",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":490,
              "y":150},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0516ea9d9c2f44ee8497edd0802448db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":150},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba94dc038d2448f49fbff4022b969543",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":176},
            "size":{
              "width":290,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_2/u5_line.png"}},
{
          "id":"4746f06ad30b4198b2ac41752088fada",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":490,
              "y":176},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8dc01cdd1f8493dab791caf75b974b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":176},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37292dfc734e4001b0444d011dd7b07c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":307},
            "size":{
              "width":290,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_2/u5_line.png"}},
{
          "id":"ec666b7e6cc84de49865f2bc26b4218f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":490,
              "y":304},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d19493a5a2bb4a63b2b7aeecdec637f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":304},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1a4b3ba931247059401d40f7648a9be",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":197},
            "size":{
              "width":290,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_2/u5_line.png"}},
{
          "id":"e85826ab437d4fbba8724e2b21e0596e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":490,
              "y":190},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"135530d1039e4aeea76f0450407c1cb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":490,
                  "y":190},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"017c715a7eac4bd9a251f85c72726ba6",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":80},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on (Shape) equal to &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8cad1f2b33864084ab593654d025afb8"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":100,
              "height":30,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":0,
                "b":0,
                "a":1},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"20a4634efa27496594abafd08189ec36",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8cad1f2b33864084ab593654d025afb8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCC0000},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/page_2/u15.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"2508"}},
{
              "column0":{
                "type":"text",
                "text":"2200"}},
{
              "column0":{
                "type":"text",
                "text":"2051-2080"}}],
          "dataProps":["column0"]},
{
          "id":"0a8aff630598409d92989049e493a94d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":156},
            "size":{
              "width":290,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_2/u5_line.png"}},
{
          "id":"c288d1ee8b2d4ea8950390368ef8b846",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":340},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on (Shape) equal to &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6416b57c83de4eb88a3fc7d2c7ab4032"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":100,
              "height":30,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"e454a3fb7acc4ec897a035fb78c6425c",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC00},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6416b57c83de4eb88a3fc7d2c7ab4032",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00CC00},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/page_2/u1.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"1669-1682"}},
{
              "column0":{
                "type":"text",
                "text":"1605-1621"}},
{
              "column0":{
                "type":"text",
                "text":"1498-1516"}}],
          "dataProps":["column0"]},
{
          "id":"3fd9cbf052d847caa8ac62eca5b80692",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":30},
            "size":{
              "width":267,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a54b5bcc346948b4a0ff199436a6d142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":30},
                "size":{
                  "width":267,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3870d1b2b41847d697a7e792fe91c96a":{
      "scriptId":"u0"},
    "88fd5f2766a2414ea0d27039a9ccb4b3":{
      "scriptId":"u1"},
    "bd70f4f719524170be977338a50e1960":{
      "scriptId":"u2"},
    "b986408168f54c759e7a876778397088":{
      "scriptId":"u3"},
    "0516ea9d9c2f44ee8497edd0802448db":{
      "scriptId":"u4"},
    "ba94dc038d2448f49fbff4022b969543":{
      "scriptId":"u5"},
    "4746f06ad30b4198b2ac41752088fada":{
      "scriptId":"u6"},
    "a8dc01cdd1f8493dab791caf75b974b5":{
      "scriptId":"u7"},
    "37292dfc734e4001b0444d011dd7b07c":{
      "scriptId":"u8"},
    "ec666b7e6cc84de49865f2bc26b4218f":{
      "scriptId":"u9"},
    "d19493a5a2bb4a63b2b7aeecdec637f1":{
      "scriptId":"u10"},
    "d1a4b3ba931247059401d40f7648a9be":{
      "scriptId":"u11"},
    "e85826ab437d4fbba8724e2b21e0596e":{
      "scriptId":"u12"},
    "135530d1039e4aeea76f0450407c1cb5":{
      "scriptId":"u13"},
    "017c715a7eac4bd9a251f85c72726ba6":{
      "scriptId":"u14"},
    "20a4634efa27496594abafd08189ec36":{
      "scriptId":"u15"},
    "8cad1f2b33864084ab593654d025afb8":{
      "scriptId":"u16"},
    "0a8aff630598409d92989049e493a94d":{
      "scriptId":"u17"},
    "c288d1ee8b2d4ea8950390368ef8b846":{
      "scriptId":"u18"},
    "e454a3fb7acc4ec897a035fb78c6425c":{
      "scriptId":"u19"},
    "6416b57c83de4eb88a3fc7d2c7ab4032":{
      "scriptId":"u20"},
    "3fd9cbf052d847caa8ac62eca5b80692":{
      "scriptId":"u21"},
    "a54b5bcc346948b4a0ff199436a6d142":{
      "scriptId":"u22"}}});